name: Flujo de trabajo nuevo
on:
  workflow_dispatch: #se dispara manualmente
  issues:
    types: [opened]  #Se dispara al crear un nuevo issue
  project_column:
    types: [moved] #se dispara al moverse entre columnas
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v3 #lmacenar en caché las dependencias
      with:
        path: prime-numbers
        key: ${{ runner.os }}-primes

